import { useCallback, useEffect } from 'react';
import Head from 'next/head';

import { getAll } from '@/services/product';

export default function Home() {
  const fetchProducts = useCallback(async () => {
    try {
      const data = await getAll({});
      console.log(data);
    } catch (e) {
      console.log(e);
    }
  }, []);

  useEffect(() => {
    fetchProducts();
  }, [fetchProducts]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello World</div>
    </>
  );
}
